version: '3'

networks:
  app: 
    driver: bridge

volumes:
  # db:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ${DB_PATH}
  code:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${APP_PATH}

services:
  # postgres:
  #   build: requirements/postgres
  #   restart: always
  #   env_file: 
  #     .env
  #   container_name: postgres
  #   volumes:
  #     - db:/var/lib/postgresql/data
  #   networks:
  #     - app

  gcc:
    build: requirements/gcc
    restart: always
    volumes:
      - code:/var/backendschool21
    networks:
      - app
    container_name: gcc
    ports:
      - "80:80"
    env_file: 
      .env
    depends_on:
      - postgres

  # adminer:
  #   build: requirements/adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - app
  #   container_name: adminer